config/routes.rb
Rails.application.routes.draw do
  resources :deck
  resources :deck_builder, only: [:new, :create]


  root to: "deck#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :deck

  def set_attributes(retreat_cost, types, attacks, weaknesses, resistances)
    @retreat_cost = retreat_cost
    @types = types
    @attacks = attacks
    @weaknesses = weaknesses
    @resistances = resistances
  end

    def retreat_cost
      @retreat_cost
    end

    def types
      @types
    end

    def attacks
      @attacks
    end

    def weaknesses
      @weaknesses
    end

    def resistances
      @resistances
    end
  # {
  #   "id": "xy7-54",
  #   "name": "Gardevoir",
  #   "nationalPokedexNumber": 282,
  #   "imageUrl": "https://s3.amazonaws.com/pokemontcg/xy7/54.png",
  #   "subtype": "Stage 2",
  #   "supertype": "Pokémon",
  #   "ability": {
  #     "name": "Bright Heal",
  #     "text": "Once during your turn (before your attack), you may heal 20 damage from each of your Pokémon."
  #   },
  #   "hp": "130",
  #   "retreatCost": [
  #     "Colorless",
  #     "Colorless"
  #   ],
  #   "number": "54",
  #   "artist": "TOKIYA",
  #   "rarity": "Rare Holo",
  #   "series": "XY",
  #   "set": "Ancient Origins",
  #   "setCode": "xy7",
  #   "types": [
  #     "Fairy"
  #   ],
  #   "attacks": [
  #     {
  #     "cost": [
  #       "Colorless",
  #       "Colorless",
  #       "Colorless"
  #     ],
  #     "name": "Telekinesis",
  #     "text": "This attack does 50 damage to 1 of your opponent's Pokémon. This attack's damage isn't affected by Weakness or Resistance.",
  #     "damage": "",
  #     "convertedEnergyCost": 3
  #     }
  #   ],
  #   "weaknesses": [
  #     {
  #       "type": "Metal",
  #       "value": "×2"
  #     }
  #   ],
  #   "resistances": [
  #     {
  #       "type": "Darkness",
  #       "value": "-20"
  #     }
end

app/models/deck.rb
class Deck < ApplicationRecord
  def complete?
    cards.length >= 60 ? true : false
  end

  def add_cards(card, number=1)
    number.times do card
      entry = Card.create(deck_id: id,
                          card_id: card.id,
                          name: card.name,
                          national_pokedex_number: card.national_pokedex_number,
                          image_url: card.image_url,
                          subtype: card.subtype,
                          supertype: card.supertype,
                          hp: card.hp,
                          number: card.number,
                          artist: card.artist,
                          rarity: card.rarity,
                          series: card.series,
                          set: card.set,
                          set_code: card.set_code
                         )
      entry.set_attributes(card.retreat_cost,
                           card.types,
                           card.attacks,
                           card.weaknesses,
                           card.resistances)
    end
    complete?
  end

  def name
    'example name'
  end

  def cards
    Card.where(deck_id: id)
  end

  def wins
    0
  end

  def losses
    0
  end

  def basic_pokemon
    basic_pokemon = []
    cards.each do |card|
      if card.subtype == 'Stage 1'
        basic_pokemon << card
      end
    end
    basic_pokemon
  end

  def evolved_pokemon
    evolved_pokemon = []
    cards.each do |card|
      if card.subtype != 'Stage 1' && card.supertype == 'Pokémon'
        evolved_pokemon << card
      end
    end
    evolved_pokemon
  end

  def trainers
    trainers = []
    cards.each do |card|
      if card.supertype == 'Trainer'
        trainers << card
      end
    end
    trainers
  end

  def type
    types = {}
    types.default = 0

    cards.each do |card|
      card.types.each{|type|types[type]+=1} if card.types
    end
    ret = ''
    types.max_by{|type, qty| ret = type}
    ret
  end

  def energy
    energy = {}
    energy.default = [0,'']
    cards.each do |card|
      if card.supertype == 'Energy'
        energy[card.name] = [energy[card.name][0] += 1, card.image_url]
      end
    end
    energy
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/deck_builder_controller.rb
class DeckBuilderController < ApplicationController
end

app/controllers/deck_controller.rb
class DeckController < ApplicationController

  def index
    @decks = Deck.all
  end

  def new
    @deck = Deck.new
  end

  def create
  end

  def show
    @deck = Deck.find(params[:id]).assemble
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/deck_builder_helper.rb
module DeckBuilderHelper
end

app/helpers/deck_helper.rb
module DeckHelper
end

app/views/deck/_energy.html.erb
<% deck.energy.each do |name, atributes| %>
  <p><%= atributes[0] %>&times; <%=image_tag(atributes[1], alt: name, width: '36px', height: '50px')%></p>
<% end %>

app/views/deck/index.html.erb
<h2>Decks</h2>

<%= link_to 'Build your own deck', new_deck_path, class: 'btn btn-primary col-md-2 pull-left' %>


<table class="table table-striped decks text-center">
  <thead>
    <tr>
      <th></th>
      <th>Created By</th>
      <th>Date Created</th>
      <th>Record</th>
      <th>Type</th>
      <th>Basic Pokemon</th>
      <th>Evolved Pokemon</th>
      <th>Trainers</th>
      <th>Energy</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <%- @decks.each do |deck| -%>
      <tr>
        <td><%= deck.name %></td>
        <td><%= l(deck.created_at, format: :short) %></td>
        <td><%= deck.wins %>/<%= deck.losses %></td>
        <td><%= deck.type %></td>
        <td><%= deck.basic_pokemon.length %></td>
        <td><%= deck.evolved_pokemon.length %></td>
        <td><%= deck.trainers.length %></td>
        <td><%= render "energy", deck: deck %></td>
        <td><%= button_to 'show deck', deck_path(deck), method: 'get', class: 'btn btn-info'%></td>
      </tr>
    <%- end -%>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DeckBuilder</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>